export const userConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  ADD_GENDER_REQUEST: " ADD_GENDER_REQUEST",
  ADD_GENDER_SUCCESS: " ADD_GENDER_SUCCESS",
  ADD_GENDER_FAILURE: " ADD_GENDER_FAILURE",

  ADD_SUBJECT_REQUEST: " ADD_SUBJECT_REQUEST",
  ADD_SUBJECT_SUCCESS: " ADD_SUBJECT_SUCCESS",
  ADD_SUBJECT_FAILURE: " ADD_SUBJECT_FAILURE",

  ADD_ADMIN_REQUEST: "ADD_ADMIN_REQUEST",
  ADD_ADMIN_SUCCESS: "ADD_ADMIN_SUCCESS",
  ADD_ADMIN_FAILURE: "ADD_ADMIN_FAILURE",

  ADD_TICKET_REQUEST: "ADD_TICKET_REQUEST",
  ADD_TICKET_SUCCESS: "ADD_TICKET_SUCCESS",
  ADD_TICKET_FAILURE: "ADD_TICKET_FAILURE",

  CLEAR: "CLEAR"
};
