export const userConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  ADD_GENDER_REQUEST: " ADD_GENDER_REQUEST",
  ADD_GENDER_SUCCESS: " ADD_GENDER_SUCCESS",
  ADD_GENDER_FAILURE: " ADD_GENDER_FAILURE",

  ADD_SUBJECT_REQUEST: " ADD_SUBJECT_REQUEST",
  ADD_SUBJECT_SUCCESS: " ADD_SUBJECT_SUCCESS",
  ADD_SUBJECT_FAILURE: " ADD_SUBJECT_FAILURE",

  ADD_ADMIN_REQUEST: "ADD_ADMIN_REQUEST",
  ADD_ADMIN_SUCCESS: "ADD_ADMIN_SUCCESS",
  ADD_ADMIN_FAILURE: "ADD_ADMIN_FAILURE",

  ADD_TICKET_REQUEST: "ADD_TICKET_REQUEST",
  ADD_TICKET_SUCCESS: "ADD_TICKET_SUCCESS",
  ADD_TICKET_FAILURE: "ADD_TICKET_FAILURE",

  GET_STUDENT_REQUEST: "GET_STUDENT_REQUEST",
  GET_STUDENT_SUCCESS: "GET_STUDENT_SUCCESS",
  GET_STUDENT_FAILURE: "GET_STUDENT_FAILURE",

  GET_TUTORS_REQUEST: "GET_TUTORS_REQUEST",
  GET_TUTORS_SUCCESS: "GET_TUTORS_SUCCESS",
  GET_TUTORS_FAILURE: "GET_TUTORS_FAILURE",

  CHANGE_STATUS_REQUEST: "CHANGE_STATUS_REQUEST",
  CHANGE_STATUS_SUCCESS: "CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "CHANGE_STATUS_FAILURE",

  ADD_SUBSCRIPTION_REQUEST: "ADD_SUBSCRIPTION_REQUEST",
  ADD_SUBSCRIPTION_SUCCESS: "ADD_SUBSCRIPTION_SUCCESS",
  ADD_SUBSCRIPTION_FAILURE: "ADD_SUBSCRIPTION_FAILURE",

  GET_PRICEBUCKET_REQUEST: "GET_PRICEBUCKET_REQUEST",
  GET_PRICEBUCKET_SUCCESS: "GET_PRICEBUCKET_SUCCESS",
  GET_PRICEBUCKET_FAILURE: "GET_PRICEBUCKET_FAILURE",

  GET_SESSION_REQUEST: "GET_SESSION_REQUEST",
  GET_SESSION_SUCCESS: "GET_SESSION_SUCCESS",
  GET_SESSION_FAILURE: "GET_SESSION_FAILURE",

  CLEAR: "CLEAR"
};
